import { List } from "@mantlebee/ts-core";

import { GenericItem } from "./types";

export const GenericItems: List<GenericItem> = [
  {
    id: 1,
    firstName: "Ut",
    lastName: "Consectetur",
    username: "utconsectetur",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "ut.consectetur@mailinator.com",
    age: 30,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 2,
    firstName: "Viverra",
    lastName: "Congue",
    username: "viverracongue",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "viverra.congue@mailinator.com",
    age: 49,
    gender: "M",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 3,
    firstName: "Egestas",
    lastName: "Amet",
    username: "egestasamet",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "egestas.amet@mailinator.com",
    age: 52,
    gender: "M",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 4,
    firstName: "Lorem",
    lastName: "Diam",
    username: "loremdiam",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "lorem.diam@mailinator.com",
    age: 20,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 5,
    firstName: "Praesent",
    lastName: "Congue",
    username: "praesentcongue",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "praesent.congue@mailinator.com",
    age: 34,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 6,
    firstName: "Vehicula",
    lastName: "Viverra",
    username: "vehiculaviverra",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "vehicula.viverra@mailinator.com",
    age: 54,
    gender: "M",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 7,
    firstName: "Praesent",
    lastName: "Ultricies",
    username: "praesentultricies",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "praesent.ultricies@mailinator.com",
    age: 35,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 8,
    firstName: "Diam",
    lastName: "Dolor",
    username: "diamdolor",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "diam.dolor@mailinator.com",
    age: 26,
    gender: "F",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 9,
    firstName: "Amet",
    lastName: "Lorem",
    username: "ametlorem",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "amet.lorem@mailinator.com",
    age: 47,
    gender: "M",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 10,
    firstName: "Ligula",
    lastName: "Ipsum",
    username: "ligulaipsum",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "ligula.ipsum@mailinator.com",
    age: 18,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 11,
    firstName: "Egestas",
    lastName: "Ultricies",
    username: "egestasultricies",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "egestas.ultricies@mailinator.com",
    age: 30,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 12,
    firstName: "Vehicula",
    lastName: "Adipiscing",
    username: "vehiculaiscing",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "vehicula.adipiscing@mailinator.com",
    age: 49,
    gender: "M",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 13,
    firstName: "Enim",
    lastName: "Eget",
    username: "enimeget",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "enim.eget@mailinator.com",
    age: 52,
    gender: "M",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 14,
    firstName: "Lectus",
    lastName: "Consectetur",
    username: "lectusconsectetur",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "lectus.consectetur@mailinator.com",
    age: 20,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 15,
    firstName: "Ultricies",
    lastName: "Libero",
    username: "ultricieslibero",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "ultricies.libero@mailinator.com",
    age: 34,
    gender: "M",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 16,
    firstName: "Augue",
    lastName: "Porta",
    username: "augueporta",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "augue.porta@mailinator.com",
    age: 54,
    gender: "M",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 17,
    firstName: "Consectetur",
    lastName: "Ligula",
    username: "consecteturligula",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "consectetur.ligula@mailinator.com",
    age: 35,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 18,
    firstName: "Mattis",
    lastName: "Ipsum",
    username: "mattisipsum",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "mattis.ipsum@mailinator.com",
    age: 29,
    gender: "F",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 19,
    firstName: "Quam",
    lastName: "Congue",
    username: "quamcongue",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "quam.congue@mailinator.com",
    age: 52,
    gender: "M",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 20,
    firstName: "Mollis",
    lastName: "Donec",
    username: "mollisdonec",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "mollis.donec@mailinator.com",
    age: 18,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 21,
    firstName: "Praesent",
    lastName: "Consectetur",
    username: "praesentconsectetur",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "praesent.consectetur@mailinator.com",
    age: 30,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 22,
    firstName: "Congue",
    lastName: "Tortor",
    username: "conguetortor",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "congue.tortor@mailinator.com",
    age: 49,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 23,
    firstName: "Amet",
    lastName: "Consectetur",
    username: "",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "amet.consectetur@mailinator.com",
    age: 67,
    gender: "M",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 24,
    firstName: "Consectetur",
    lastName: "Mollis",
    username: "consmollis",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "cons.mollis@mailinator.com",
    age: 20,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 25,
    firstName: "Congue",
    lastName: "congueamet",
    username: "amet",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "congue.amet@mailinator.com",
    age: 34,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 26,
    firstName: "Lorem",
    lastName: "Tortor",
    username: "loremtortor",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "lorem.tortor@mailinator.com",
    age: 54,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 27,
    firstName: "Donec",
    lastName: "Libero",
    username: "doneclibero",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "donec.libero@mailinator.com",
    age: 35,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 28,
    firstName: "Acsit",
    lastName: "Maecenas",
    username: "acsitmaecenas",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "acsit.maecenas@mailinator.com",
    age: 26,
    gender: "F",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 29,
    firstName: "Dolor",
    lastName: "Consectetur",
    username: "dolorconsectetur",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "dolor.consectetur@mailinator.com",
    age: 54,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 30,
    firstName: "Elit",
    lastName: "Elit",
    username: "Lacinia",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "elit.lacinia@mailinator.com",
    age: 18,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 31,
    firstName: "Donec",
    lastName: "Donec",
    username: "Nam",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "donec.nam@mailinator.com",
    age: 30,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 32,
    firstName: "Consectetur",
    lastName: "Porta",
    username: "consecteturporta",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "consectetur.porta@mailinator.com",
    age: 49,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 33,
    firstName: "Enim",
    lastName: "Eget",
    username: "enimeget",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "enim.eget@mailinator.com",
    age: 52,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 34,
    firstName: "Tincidunt",
    lastName: "Enim",
    username: "tinciduntenim",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "tincidunt.enim@mailinator.com",
    age: 20,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 35,
    firstName: "Diam",
    lastName: "Lorema",
    username: "diamlorema",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "diam.lorema@mailinator.com",
    age: 34,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 36,
    firstName: "Ultricies",
    lastName: "Libero",
    username: "ultricieslibero",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "ultricies.libero@mailinator.com",
    age: 54,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 37,
    firstName: "Augue",
    lastName: "Porta",
    username: "augueporta",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "augue.porta@mailinator.com",
    age: 35,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 38,
    firstName: "Dolor",
    lastName: "Donec",
    username: "dolordonec",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "dolor.donec@mailinator.com",
    age: 26,
    gender: "F",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 39,
    firstName: "Enim",
    lastName: "Enim",
    username: "Diam",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "enim.diam@mailinator.com",
    age: 54,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 40,
    firstName: "Porta",
    lastName: "Egestas",
    username: "portaegestas",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "porta.egestas@mailinator.com",
    age: 18,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 41,
    firstName: "Praesent",
    lastName: "Maecenas",
    username: "praesentmaecenas",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "praesent.maecenas@mailinator.com",
    age: 30,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 42,
    firstName: "Adipiscing",
    lastName: "Quam",
    username: "adipiscingquam",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "adipiscing.quam@mailinator.com",
    age: 49,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 43,
    firstName: "Consectetur",
    lastName: "Antea",
    username: "consecteturantea",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "consectetur.antea@mailinator.com",
    age: 52,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 44,
    firstName: "Praesent",
    lastName: "Diam",
    username: "praesentdiam",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "praesentdiam@mailinator.com",
    age: 20,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 45,
    firstName: "Nam",
    lastName: "Lorem",
    username: "namlorem",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "nam.lorem@mailinator.com",
    age: 34,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 46,
    firstName: "Elit",
    lastName: "Lectus",
    username: "elitlectus",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "elitlectus@mailinator.com",
    age: 54,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 47,
    firstName: "Praesent",
    lastName: "Sed",
    username: "praesentsed",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "praesentsed@mailinator.com",
    age: 35,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 48,
    firstName: "Egestas",
    lastName: "Libero",
    username: "egestaslibero",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "egestaslibero@mailinator.com",
    age: 26,
    gender: "F",
    married: true,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 49,
    firstName: "Lectus",
    lastName: "Porta",
    username: "lectusporta",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "lectus.porta@mailinator.com",
    age: 54,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
  {
    id: 50,
    firstName: "Maecenas",
    lastName: "Mattis",
    username: "maecenasmattis",
    avatar: "https://www.gravatar.com/avatar/00000000000000000000000000000000",
    badge: "fas fa-alien-monster",
    email: "maecenasmattis@mailinator.com",
    age: 18,
    gender: "M",
    married: false,
    marriedOn: new Date(),
    phone: "(+1) 000 0000 000",
    website: "example.com",
    __backgroundColor__: "lightseagreen",
    __foregroundColor__: "white",
  },
];
